import { chromium } from "playwright";
const b = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium-1194/chrome-linux/chrome' });
const c = await b.newContext({ viewport: { width: 1280, height: 1000 } });
const p = await c.newPage();
await p.goto("http://localhost:3000/account", { waitUntil: "domcontentloaded" });
await p.waitForTimeout(800);
await p.fill('input[name="phone"]', "+79280000001");
await p.fill('input[name="password"]', "demo1234");
await p.click('button[type="submit"]');
await p.waitForTimeout(2000);
await p.screenshot({ path: "shots/lk-overview.png", fullPage: true });
console.log("overview", p.url());
await p.goto("http://localhost:3000/account/addresses", { waitUntil: "domcontentloaded" });
await p.waitForTimeout(900);
await p.screenshot({ path: "shots/lk-addresses.png", fullPage: true });
console.log("addresses");
await p.goto("http://localhost:3000/account/profile", { waitUntil: "domcontentloaded" });
await p.waitForTimeout(900);
await p.screenshot({ path: "shots/lk-profile.png", fullPage: true });
console.log("profile");
await b.close();
