// Соответствие «slug товара → локальные фото» (перенесены со старого сайта
// biohayat.ru, сконвертированы в WebP, лежат в public/legacy/ и запекаются в образ).
// Привязываются к товарам скриптом scripts/import-legacy-photos.ts (pnpm db:import-photos).

export const legacyImages: Record<string, string[]> = {
  "metodrol": ["/legacy/metodrol-1.webp"],
  "magnesium-b6": ["/legacy/magnesium-b6-1.webp"],
  "senol": ["/legacy/senol-1.webp"],
  "chernyy-tmin-kids": ["/legacy/chernyy-tmin-kids-1.webp", "/legacy/chernyy-tmin-kids-2.webp"],
  "darb-saraton": ["/legacy/darb-saraton-1.webp", "/legacy/darb-saraton-2.webp", "/legacy/darb-saraton-3.webp"],
  "lotus-no-fat-zhiroszhigatel": ["/legacy/lotus-no-fat-zhiroszhigatel-1.webp"],
  "omega-3-detskiy": ["/legacy/omega-3-detskiy-1.webp", "/legacy/omega-3-detskiy-2.webp"],
  "retinolin": ["/legacy/retinolin-1.webp", "/legacy/retinolin-2.webp"],
  "pancreatin-hayat": ["/legacy/pancreatin-hayat-1.webp", "/legacy/pancreatin-hayat-2.webp"],
  "vitamin-d3-k2": ["/legacy/vitamin-d3-k2-1.webp"],
  "vitamin-d3-kids": ["/legacy/vitamin-d3-kids-1.webp"],
  "vitamin-c": ["/legacy/vitamin-c-1.webp"],
  "sinus-kids": ["/legacy/sinus-kids-1.webp", "/legacy/sinus-kids-2.webp", "/legacy/sinus-kids-3.webp"],
  "sinus": ["/legacy/sinus-1.webp"],
  "sidra": ["/legacy/sidra-1.webp", "/legacy/sidra-2.webp"],
  "marine-collagen": ["/legacy/marine-collagen-1.webp"],
  "lotus-no-fat-ochischenie": ["/legacy/lotus-no-fat-ochischenie-1.webp", "/legacy/lotus-no-fat-ochischenie-2.webp", "/legacy/lotus-no-fat-ochischenie-3.webp"],
  "kust-al-hindi-kids": ["/legacy/kust-al-hindi-kids-1.webp"],
  "kyst-al-hindi-maslo": ["/legacy/kyst-al-hindi-maslo-1.webp", "/legacy/kyst-al-hindi-maslo-2.webp"],
  "ginkgo-biloba-kids": ["/legacy/ginkgo-biloba-kids-1.webp"],
  "enurel-forte": ["/legacy/enurel-forte-1.webp", "/legacy/enurel-forte-2.webp"],
  "kardiofore": ["/legacy/kardiofore-1.webp", "/legacy/kardiofore-2.webp"],
  "nefrolgin": ["/legacy/nefrolgin-1.webp", "/legacy/nefrolgin-2.webp"],
  "azitronil": ["/legacy/azitronil-1.webp", "/legacy/azitronil-2.webp"],
  "tuberkulin": ["/legacy/tuberkulin-1.webp", "/legacy/tuberkulin-2.webp"],
  "diaforte": ["/legacy/diaforte-1.webp", "/legacy/diaforte-2.webp"],
  "alkogen": ["/legacy/alkogen-1.webp", "/legacy/alkogen-2.webp"],
  "uretrofrom": ["/legacy/uretrofrom-1.webp", "/legacy/uretrofrom-2.webp"],
  "tahsis": ["/legacy/tahsis-1.webp", "/legacy/tahsis-2.webp"],
  "med-lipovyy": ["/legacy/med-lipovyy-1.webp", "/legacy/med-lipovyy-2.webp"],
  "med-raznotrave": ["/legacy/med-raznotrave-1.webp"],
  "omega-3-250-mozg": ["/legacy/omega-3-250-mozg-1.webp", "/legacy/omega-3-250-mozg-2.webp"],
  "kyst-al-hindi-bahri-100": ["/legacy/kyst-al-hindi-bahri-100-1.webp", "/legacy/kyst-al-hindi-bahri-100-2.webp", "/legacy/kyst-al-hindi-bahri-100-3.webp"],
  "chernyy-tmin-100": ["/legacy/chernyy-tmin-100-1.webp", "/legacy/chernyy-tmin-100-2.webp"],
  "habbur-rashad-100": ["/legacy/habbur-rashad-100-1.webp", "/legacy/habbur-rashad-100-2.webp", "/legacy/habbur-rashad-100-3.webp"],
  "hilba-1kg": ["/legacy/hilba-1kg-1.webp"],
  "vitamix-energy-300": ["/legacy/vitamix-energy-300-1.webp"],
  "maslo-chernogo-tmina-100": ["/legacy/maslo-chernogo-tmina-100-1.webp", "/legacy/maslo-chernogo-tmina-100-2.webp"],
  "habbur-rashad-500": ["/legacy/habbur-rashad-500-1.webp", "/legacy/habbur-rashad-500-2.webp", "/legacy/habbur-rashad-500-3.webp"],
  "chernyy-tmin-500": ["/legacy/chernyy-tmin-500-1.webp", "/legacy/chernyy-tmin-500-2.webp"],
  "sanna-va-sunut": ["/legacy/sanna-va-sunut-1.webp", "/legacy/sanna-va-sunut-2.webp"],
  "kyst-al-hindi-bahri-500": ["/legacy/kyst-al-hindi-bahri-500-1.webp", "/legacy/kyst-al-hindi-bahri-500-2.webp", "/legacy/kyst-al-hindi-bahri-500-3.webp"],
  "omega-3-250mg": ["/legacy/omega-3-250mg-1.webp"],
  "omega-3-kyst": ["/legacy/omega-3-kyst-1.webp", "/legacy/omega-3-kyst-2.webp"],
  "miksamel": ["/legacy/miksamel-1.webp", "/legacy/miksamel-2.webp"],
  "mics-camel": ["/legacy/mics-camel-1.webp", "/legacy/mics-camel-2.webp", "/legacy/mics-camel-3.webp"],
  "maslo-tmina-omega": ["/legacy/maslo-tmina-omega-1.webp"],
  "al-kyst-al-hindi": ["/legacy/al-kyst-al-hindi-1.webp"],
  "al-kust-al-hindi-kids": ["/legacy/al-kust-al-hindi-kids-1.webp"],
  "kunzhutnoe-maslo": ["/legacy/kunzhutnoe-maslo-1.webp", "/legacy/kunzhutnoe-maslo-2.webp"],
  "kostus": ["/legacy/kostus-1.webp", "/legacy/kostus-2.webp"],
  "camel-milk": ["/legacy/camel-milk-1.webp", "/legacy/camel-milk-2.webp"],
  "ziflaks": ["/legacy/ziflaks-1.webp", "/legacy/ziflaks-2.webp"],
  "dikloalam": ["/legacy/dikloalam-1.webp", "/legacy/dikloalam-2.webp"],
  "darb-sihr-toksiny": ["/legacy/darb-sihr-toksiny-1.webp", "/legacy/darb-sihr-toksiny-2.webp", "/legacy/darb-sihr-toksiny-3.webp"],
  "darb-al-hayat": ["/legacy/darb-al-hayat-1.webp", "/legacy/darb-al-hayat-2.webp"],
  "darb-al-amin": ["/legacy/darb-al-amin-1.webp", "/legacy/darb-al-amin-2.webp"],
  "vitaminnyy-kompleks": ["/legacy/vitaminnyy-kompleks-1.webp", "/legacy/vitaminnyy-kompleks-2.webp", "/legacy/vitaminnyy-kompleks-3.webp"],
  "vitamin-d3-600": ["/legacy/vitamin-d3-600-1.webp", "/legacy/vitamin-d3-600-2.webp"],
  "vitamin-d3-detskiy": ["/legacy/vitamin-d3-detskiy-1.webp"],
  "balzam-6": ["/legacy/balzam-6-1.webp", "/legacy/balzam-6-2.webp"],
  "amiksifil": ["/legacy/amiksifil-1.webp", "/legacy/amiksifil-2.webp", "/legacy/amiksifil-3.webp"],
  "amiksifil-detskiy": ["/legacy/amiksifil-detskiy-1.webp"],
  "women-health": ["/legacy/women-health-1.webp", "/legacy/women-health-2.webp"],
  "tsetriflin": ["/legacy/tsetriflin-1.webp", "/legacy/tsetriflin-2.webp"],
  "kordeksin": ["/legacy/kordeksin-1.webp"],
  "darb-sihr-besplodie": ["/legacy/darb-sihr-besplodie-1.webp", "/legacy/darb-sihr-besplodie-2.webp"],
  "ginkgo-biloba-kognitiv": ["/legacy/ginkgo-biloba-kognitiv-1.webp"],
  "akorin": ["/legacy/akorin-1.webp", "/legacy/akorin-2.webp"],
  "tminnoe-maslo-d3": ["/legacy/tminnoe-maslo-d3-1.webp"],
  "yablochnyy-uksus": ["/legacy/yablochnyy-uksus-1.webp", "/legacy/yablochnyy-uksus-2.webp"],
  "maslo-chernogo-tmina-250": ["/legacy/maslo-chernogo-tmina-250-1.webp", "/legacy/maslo-chernogo-tmina-250-2.webp"],
  "tireo-forte": ["/legacy/tireo-forte-1.webp", "/legacy/tireo-forte-2.webp"],
  "doxilin": ["/legacy/doxilin-1.webp", "/legacy/doxilin-2.webp"],
  "darb-varam": ["/legacy/darb-varam-1.webp", "/legacy/darb-varam-2.webp"],
  "glistin": ["/legacy/glistin-1.webp", "/legacy/glistin-2.webp"],
  "andro-hayat": ["/legacy/andro-hayat-1.webp", "/legacy/andro-hayat-2.webp"],
  "omega-3-d3-kids": ["/legacy/omega-3-d3-kids-1.webp"],
  "testo-hayat": ["/legacy/testo-hayat-1.webp", "/legacy/testo-hayat-2.webp"],
  "vitamix-energy-800": ["/legacy/vitamix-energy-800-1.webp", "/legacy/vitamix-energy-800-2.webp"],
  "vitamin-e": ["/legacy/vitamin-e-1.webp", "/legacy/vitamin-e-2.webp"],
  "coenzyme-q10": ["/legacy/coenzyme-q10-1.webp", "/legacy/coenzyme-q10-2.webp"],
  "zink-magniy-b6": ["/legacy/zink-magniy-b6-1.webp"],
  "zinc-picolinate": ["/legacy/zinc-picolinate-1.webp"],
  "vitamin-d3-10000": ["/legacy/vitamin-d3-10000-1.webp"],
  "vitamin-d3-5000": ["/legacy/vitamin-d3-5000-1.webp"],
  "vitamin-d3-2000": ["/legacy/vitamin-d3-2000-1.webp", "/legacy/vitamin-d3-2000-2.webp"],
  "vitamin-a-10000": ["/legacy/vitamin-a-10000-1.webp"],
  "vitamin-a-5000": ["/legacy/vitamin-a-5000-1.webp"],
  "hyaluronic-acid": ["/legacy/hyaluronic-acid-1.webp"],
  "zhelezo-iron": ["/legacy/zhelezo-iron-1.webp"],
  "glucosamine-chondroitine-msm": ["/legacy/glucosamine-chondroitine-msm-1.webp"],
  "ginkgo-biloba-130": ["/legacy/ginkgo-biloba-130-1.webp"],
  "gaba-800": ["/legacy/gaba-800-1.webp"],
  "dmae-250": ["/legacy/dmae-250-1.webp"],
  "kollagen-govyazhiy": ["/legacy/kollagen-govyazhiy-1.webp", "/legacy/kollagen-govyazhiy-2.webp"],
  "chromium-picolinate": ["/legacy/chromium-picolinate-1.webp"],
  "biotin-5000": ["/legacy/biotin-5000-1.webp"],
  "biotin-10000": ["/legacy/biotin-10000-1.webp"],
  "5-htp-100": ["/legacy/5-htp-100-1.webp"],
  "hilba-100": ["/legacy/hilba-100-1.webp", "/legacy/hilba-100-2.webp"],
  "imbir-100": ["/legacy/imbir-100-1.webp"],
  "zarira-100": ["/legacy/zarira-100-1.webp"],
  "svechi-proktofan": ["/legacy/svechi-proktofan-1.webp"],
  "svechi-mio": ["/legacy/svechi-mio-1.webp"],
  "svechi-darb-sihr": ["/legacy/svechi-darb-sihr-1.webp"],
  "mylo-shungit": ["/legacy/mylo-shungit-1.webp", "/legacy/mylo-shungit-2.webp"],
  "mylo-spirulina": ["/legacy/mylo-spirulina-1.webp", "/legacy/mylo-spirulina-2.webp"],
  "mylo-kostus": ["/legacy/mylo-kostus-1.webp", "/legacy/mylo-kostus-2.webp"],
  "mylo-verblyuzhe": ["/legacy/mylo-verblyuzhe-1.webp", "/legacy/mylo-verblyuzhe-2.webp"],
  "med-sidra": ["/legacy/med-sidra-1.webp", "/legacy/med-sidra-2.webp"],
  "balzam-9": ["/legacy/balzam-9-1.webp", "/legacy/balzam-9-2.webp"],
  "balzam-8": ["/legacy/balzam-8-1.webp", "/legacy/balzam-8-2.webp"],
  "balzam-7": ["/legacy/balzam-7-1.webp", "/legacy/balzam-7-2.webp"],
  "balzam-5": ["/legacy/balzam-5-1.webp", "/legacy/balzam-5-2.webp"],
  "balzam-4": ["/legacy/balzam-4-1.webp", "/legacy/balzam-4-2.webp"],
  "balzam-3": ["/legacy/balzam-3-1.webp", "/legacy/balzam-3-2.webp"],
  "balzam-2": ["/legacy/balzam-2-1.webp", "/legacy/balzam-2-2.webp"],
  "balzam-1": ["/legacy/balzam-1-1.webp", "/legacy/balzam-1-2.webp"],
};
