// Каталог из 119 позиций, мигрированный с biohayat.ru (2026-05-28).
// Цены в рублях (в сид-скрипте переводятся в копейки).
// Категория назначается по ключевым словам (см. categorize() в seed.ts).

export interface SeedProduct {
  name: string;
  slug: string;
  price: number;
  oldPrice?: number;
  volume?: string;
  /** принудительная категория (slug), если автоопределение не подходит */
  cat?: string;
}

export const seedProducts: SeedProduct[] = [
  { name: "Методрол — улучшает усвоение пищи", slug: "metodrol", price: 900, cat: "zhkt" },
  { name: "Magnesium + B6", slug: "magnesium-b6", price: 800, cat: "vitaminy-mineraly" },
  { name: "Сенол — от хронических запоров", slug: "senol", price: 500, cat: "zhkt" },
  { name: "Чёрный тмин Kids (детский)", slug: "chernyy-tmin-kids", price: 700, cat: "dlya-detey" },
  { name: "Дарб Саратон", slug: "darb-saraton", price: 6000, cat: "balzamy" },
  { name: "Lotus No Fat — жиросжигатель в капсулах", slug: "lotus-no-fat-zhiroszhigatel", price: 1200, cat: "dlya-pohudeniya" },
  { name: "Омега-3 детский (Omega-3 Kids)", slug: "omega-3-detskiy", price: 650, cat: "dlya-detey" },
  { name: "Retinolin (Ретинолин)", slug: "retinolin", price: 3000, cat: "krasota" },
  { name: "Панкреатин (Pancreatin Hayat)", slug: "pancreatin-hayat", price: 900, cat: "zhkt" },
  { name: "Vitamin D3 + K2 — укрепление костей", slug: "vitamin-d3-k2", price: 1300, cat: "vitaminy-mineraly" },
  { name: "Vitamin D3 Kids", slug: "vitamin-d3-kids", price: 500, cat: "dlya-detey" },
  { name: "Vitamin C", slug: "vitamin-c", price: 900, cat: "immunitet" },
  { name: "Sinus Kids — при гайморите", slug: "sinus-kids", price: 450, cat: "dlya-detey" },
  { name: "Sinus — при гайморите", slug: "sinus", price: 450, cat: "immunitet" },
  { name: "Sidra — препятствует выпадению волос", slug: "sidra", price: 700, cat: "krasota" },
  { name: "Marine Collagen (морской коллаген)", slug: "marine-collagen", price: 1100, cat: "krasota" },
  { name: "Lotus No Fat — очищение от глистов", slug: "lotus-no-fat-ochischenie", price: 700, cat: "zhkt" },
  { name: "Kust Al Hindi Kids", slug: "kust-al-hindi-kids", price: 450, cat: "dlya-detey" },
  { name: "Кыст аль-Хинди — масло, омолаживает кожу", slug: "kyst-al-hindi-maslo", price: 600, cat: "masla" },
  { name: "Гинкго Билоба — капли (Kids)", slug: "ginkgo-biloba-kids", price: 500, cat: "dlya-detey" },
  { name: "Enurel Forte — мочегонное, спазмолитическое", slug: "enurel-forte", price: 900, cat: "mochepolovaya-sistema" },
  { name: "Кардиофоре — для сердечно-сосудистой системы", slug: "kardiofore", price: 1000, cat: "vitaminy-mineraly" },
  { name: "Нефролгин — улучшает работу почек", slug: "nefrolgin", price: 1000, cat: "mochepolovaya-sistema" },
  { name: "Азитронил — при ангине", slug: "azitronil", price: 1000, cat: "immunitet" },
  { name: "Туберкулин", slug: "tuberkulin", price: 3000, cat: "immunitet" },
  { name: "Диафорте — при сахарном диабете", slug: "diaforte", price: 1000, cat: "endokrinnaya" },
  { name: "Алкоген — для отвращения к алкоголю", slug: "alkogen", price: 900, oldPrice: 1500, cat: "nervnaya-sistema" },
  { name: "Уретрофром — для мочеполовой системы", slug: "uretrofrom", price: 1000, cat: "mochepolovaya-sistema" },
  { name: "Тахсис — для похудения", slug: "tahsis", price: 1000, cat: "dlya-pohudeniya" },
  { name: "Мёд липовый — укрепляет иммунитет", slug: "med-lipovyy", price: 600, oldPrice: 800, cat: "med" },
  { name: "Мёд разнотравье — комплекс витаминов и минералов", slug: "med-raznotrave", price: 600, oldPrice: 800, cat: "med" },
  { name: "Омега-3 для здоровья мозга 250 мг", slug: "omega-3-250-mozg", price: 450, oldPrice: 650, cat: "nervnaya-sistema" },
  { name: "Кыст аль-хинди и бахри — дыхательные пути, 100 г", slug: "kyst-al-hindi-bahri-100", price: 300, volume: "100 г", cat: "immunitet" },
  { name: "Чёрный тмин — укрепляет иммунитет, 100 г", slug: "chernyy-tmin-100", price: 250, volume: "100 г", cat: "semena-travy" },
  { name: "Хаббур рашад — витамины B, C, A, 100 г", slug: "habbur-rashad-100", price: 300, volume: "100 г", cat: "semena-travy" },
  { name: "Хильба — семена пажитника, 1 кг", slug: "hilba-1kg", price: 350, oldPrice: 500, volume: "1 кг", cat: "semena-travy" },
  { name: "Vitamix Energy — иммунитет", slug: "vitamix-energy-300", price: 650, cat: "immunitet" },
  { name: "Масло чёрного тмина, 100 капсул", slug: "maslo-chernogo-tmina-100", price: 800, volume: "100 капсул", cat: "masla" },
  { name: "Хаббур рашад — витамины B, C, A, 500 г", slug: "habbur-rashad-500", price: 1000, volume: "500 г", cat: "semena-travy" },
  { name: "Чёрный тмин — укрепляет иммунитет, 500 г", slug: "chernyy-tmin-500", price: 600, oldPrice: 750, volume: "500 г", cat: "semena-travy" },
  { name: "Санна-ва-Сунут — восстановление микрофлоры, 100 г", slug: "sanna-va-sunut", price: 300, volume: "100 г", cat: "zhkt" },
  { name: "Кыст аль-хинди и бахри — дыхательные пути, 500 г", slug: "kyst-al-hindi-bahri-500", price: 1000, volume: "500 г", cat: "immunitet" },
  { name: "Омега-3 250 мг — для здоровья мозга", slug: "omega-3-250mg", price: 550, cat: "nervnaya-sistema" },
  { name: "Омега-3 и Кыст аль-хинди — для сердца и сосудов", slug: "omega-3-kyst", price: 400, oldPrice: 530, cat: "vitaminy-mineraly" },
  { name: "Миксамел — разжижает кровь", slug: "miksamel", price: 1000, cat: "vitaminy-mineraly" },
  { name: "Mics-Camel — природный антибиотик", slug: "mics-camel", price: 900, oldPrice: 1200, cat: "immunitet" },
  { name: "Масло чёрного тмина (Omega 6/9/3)", slug: "maslo-tmina-omega", price: 900, oldPrice: 1100, cat: "masla" },
  { name: "Аль-кыст аль-хинди — общее укрепление организма", slug: "al-kyst-al-hindi", price: 400, oldPrice: 615, cat: "immunitet" },
  { name: "Аль-куст аль-хинди Kids — повышает иммунитет", slug: "al-kust-al-hindi-kids", price: 600, cat: "dlya-detey" },
  { name: "Кунжутное масло — для здоровья щитовидной железы", slug: "kunzhutnoe-maslo", price: 500, cat: "masla" },
  { name: "Костус — ускоряет заживление слизистых", slug: "kostus", price: 1000, cat: "immunitet" },
  { name: "Camel Milk — верблюжье молоко", slug: "camel-milk", price: 1500, cat: "vitaminy-mineraly" },
  { name: "Зифлакс — для мочевого и желчного пузыря", slug: "ziflaks", price: 1000, cat: "mochepolovaya-sistema" },
  { name: "Диклоалам — при заболеваниях мочеполовой системы", slug: "dikloalam", price: 1000, cat: "mochepolovaya-sistema" },
  { name: "Дарб Сихр — очищает от токсинов", slug: "darb-sihr-toksiny", price: 1000, cat: "balzamy" },
  { name: "Дарб Аль-Хаят — повышает устойчивость к стрессам", slug: "darb-al-hayat", price: 1600, cat: "nervnaya-sistema" },
  { name: "Дарб Аль-Амин — противовирусное и противогрибковое", slug: "darb-al-amin", price: 1600, cat: "immunitet" },
  { name: "Витаминный комплекс — укрепляет иммунитет", slug: "vitaminnyy-kompleks", price: 1000, cat: "immunitet" },
  { name: "Витамин D3 600 МЕ — стимулирует обмен веществ", slug: "vitamin-d3-600", price: 450, cat: "vitaminy-mineraly" },
  { name: "Витамин D3 детский — для правильного развития", slug: "vitamin-d3-detskiy", price: 450, oldPrice: 580, cat: "dlya-detey" },
  { name: "Бальзам №6 — для сердечно-сосудистой системы", slug: "balzam-6", price: 1200, oldPrice: 1300, cat: "balzamy" },
  { name: "Амиксифил — нормализует кровообращение", slug: "amiksifil", price: 1000, cat: "vitaminy-mineraly" },
  { name: "Амиксифил детский — укрепляет иммунитет", slug: "amiksifil-detskiy", price: 1000, cat: "dlya-detey" },
  { name: "Women Health — нормализует менструальный цикл", slug: "women-health", price: 900, oldPrice: 1100, cat: "dlya-zhenschin" },
  { name: "Цетрифлин — антигистаминное, кровоочистительное", slug: "tsetriflin", price: 1000, cat: "immunitet" },
  { name: "Кордексин — противовирусный сироп от кашля", slug: "kordeksin", price: 900, cat: "immunitet" },
  { name: "Дарб Сихр — устраняет бесплодие", slug: "darb-sihr-besplodie", price: 1100, cat: "mochepolovaya-sistema" },
  { name: "Гинкго Билоба — улучшает когнитивные функции", slug: "ginkgo-biloba-kognitiv", price: 900, oldPrice: 1350, cat: "nervnaya-sistema" },
  { name: "Акорин — защищает желудок и кишечник", slug: "akorin", price: 900, cat: "zhkt" },
  { name: "Тминное масло + Витамин D3 1000 МЕ", slug: "tminnoe-maslo-d3", price: 900, cat: "masla" },
  { name: "Яблочный уксус — помогает похудеть", slug: "yablochnyy-uksus", price: 450, cat: "dlya-pohudeniya" },
  { name: "Масло чёрного тмина, 250 капсул", slug: "maslo-chernogo-tmina-250", price: 1000, volume: "250 капсул", cat: "masla" },
  { name: "Tireo-Forte — при нарушении баланса гормонов", slug: "tireo-forte", price: 1000, cat: "endokrinnaya" },
  { name: "Doxilin (Доксилин) — для нервной системы", slug: "doxilin", price: 1000, cat: "nervnaya-sistema" },
  { name: "Darb Varam — для сердечно-сосудистой системы", slug: "darb-varam", price: 6000, cat: "balzamy" },
  { name: "Glistin (Глистин) — выводит паразитов", slug: "glistin", price: 1000, cat: "zhkt" },
  { name: "Andro-Hayat — повышает качество спермы", slug: "andro-hayat", price: 1000, cat: "dlya-muzhchin" },
  { name: "Omega-3 и витамин D3 Kids", slug: "omega-3-d3-kids", price: 700, cat: "dlya-detey" },
  { name: "Testo-Hayat — повышает мужскую силу", slug: "testo-hayat", price: 1200, oldPrice: 1550, cat: "dlya-muzhchin" },
  { name: "Витамикс (Vitamix Energy) 800", slug: "vitamix-energy-800", price: 1200, cat: "immunitet" },
  { name: "Vitamin E — замедляет процессы старения", slug: "vitamin-e", price: 800, cat: "krasota" },
  { name: "Coenzyme Q10 — сжигает жиры", slug: "coenzyme-q10", price: 1300, oldPrice: 2100, cat: "dlya-pohudeniya" },
  { name: "Цинк + Магний + B6 (ZN+MG+B6)", slug: "zink-magniy-b6", price: 1000, cat: "vitaminy-mineraly" },
  { name: "Zinc Picolinate 25 мг", slug: "zinc-picolinate", price: 700, cat: "vitaminy-mineraly" },
  { name: "Vitamin D3 10000 МЕ (250 мкг)", slug: "vitamin-d3-10000", price: 750, cat: "vitaminy-mineraly" },
  { name: "Vitamin D3 5000 МЕ (125 мкг)", slug: "vitamin-d3-5000", price: 650, cat: "vitaminy-mineraly" },
  { name: "Vitamin D3 2000 МЕ (50 мкг)", slug: "vitamin-d3-2000", price: 600, cat: "vitaminy-mineraly" },
  { name: "Vitamin A 10000 IU", slug: "vitamin-a-10000", price: 950, cat: "vitaminy-mineraly" },
  { name: "Vitamin A 5000 IU", slug: "vitamin-a-5000", price: 800, cat: "vitaminy-mineraly" },
  { name: "Hyaluronic Acid 150 мг — для суставов", slug: "hyaluronic-acid", price: 850, cat: "oporno-dvigatelnyy" },
  { name: "Железо (Iron) 20 мг — от анемии", slug: "zhelezo-iron", price: 900, cat: "vitaminy-mineraly" },
  { name: "Glucosamine Chondroitine MSM — укрепление суставов", slug: "glucosamine-chondroitine-msm", price: 1000, cat: "oporno-dvigatelnyy" },
  { name: "Ginkgo Biloba 130 мг — для мозга и нервной системы", slug: "ginkgo-biloba-130", price: 900, cat: "nervnaya-sistema" },
  { name: "GABA (ГАМК) аминомасляная кислота 800 мг", slug: "gaba-800", price: 1000, cat: "nervnaya-sistema" },
  { name: "Антидепрессант DMAE (диметиламиноэтанол) 250 мг", slug: "dmae-250", price: 900, cat: "nervnaya-sistema" },
  { name: "Коллаген говяжий (Collagen)", slug: "kollagen-govyazhiy", price: 1100, cat: "krasota" },
  { name: "Chromium Picolinate 200 мкг", slug: "chromium-picolinate", price: 900, cat: "dlya-pohudeniya" },
  { name: "Biotin 5000 мкг (витамин B7)", slug: "biotin-5000", price: 900, cat: "krasota" },
  { name: "Biotin 10000 мкг (витамин B7)", slug: "biotin-10000", price: 1100, oldPrice: 1300, cat: "krasota" },
  { name: "5-HTP гидрокситриптофан 100 мг", slug: "5-htp-100", price: 1000, oldPrice: 1250, cat: "nervnaya-sistema" },
  { name: "Хильба — семена пажитника, 100 г", slug: "hilba-100", price: 150, oldPrice: 200, volume: "100 г", cat: "semena-travy" },
  { name: "Имбирь (пряность), 100 г", slug: "imbir-100", price: 150, volume: "100 г", cat: "semena-travy" },
  { name: "Корень Зарира, 100 г — для зубов и дёсен", slug: "zarira-100", price: 250, volume: "100 г", cat: "semena-travy" },
  { name: "Свечи Проктофан (ректальные)", slug: "svechi-proktofan", price: 450, oldPrice: 650, cat: "zhkt" },
  { name: "Свечи Мио (вагинальные)", slug: "svechi-mio", price: 450, oldPrice: 755, cat: "dlya-zhenschin" },
  { name: "Свечи Дарб Сихр (вагинальные)", slug: "svechi-darb-sihr", price: 550, oldPrice: 800, cat: "dlya-zhenschin" },
  { name: "Мыло Шунгит (на основе воды)", slug: "mylo-shungit", price: 500, oldPrice: 600, cat: "krasota" },
  { name: "Мыло Спирулина с витаминами", slug: "mylo-spirulina", price: 500, oldPrice: 600, cat: "krasota" },
  { name: "Мыло Костус — для состояния кожи", slug: "mylo-kostus", price: 500, oldPrice: 600, cat: "krasota" },
  { name: "Мыло Верблюжье молоко — против морщин", slug: "mylo-verblyuzhe", price: 500, oldPrice: 600, cat: "krasota" },
  { name: "Мёд Сидра натуральный", slug: "med-sidra", price: 2000, cat: "med" },
  { name: "Бальзам №9 — очищение ЖКТ", slug: "balzam-9", price: 1200, cat: "balzamy" },
  { name: "Бальзам №8 — снижение веса", slug: "balzam-8", price: 1200, cat: "balzamy" },
  { name: "Бальзам №7 — сердечно-сосудистая система", slug: "balzam-7", price: 1200, cat: "balzamy" },
  { name: "Бальзам №5 — против вирусных инфекций", slug: "balzam-5", price: 1200, cat: "balzamy" },
  { name: "Бальзам №4 — мужская мочеполовая система", slug: "balzam-4", price: 1200, cat: "balzamy" },
  { name: "Бальзам №3 — женское здоровье", slug: "balzam-3", price: 1200, cat: "balzamy" },
  { name: "Бальзам №2 — нервная система", slug: "balzam-2", price: 1200, cat: "balzamy" },
  { name: "Бальзам №1 — суставы и ОДА", slug: "balzam-1", price: 1200, oldPrice: 1900, cat: "balzamy" },
];
